### ISSUE TITLE
Local images aren't loading on "0.1.2". On "0.1.0" they are working

### ISSUE THREAD

**Issue by zubko** [unimodules/react-native-platform#1]
I'm adding react-native-platform to the existing app. I followed the integration from demo project (https://github.com/brentvatne/my-app-with-unimodules), but all local images stopped showing up, just empty space. 

Using the same version of `react-native-platform` as in `my-app-with-unimodules` fixed the issue with images.
(But FileSystem.documentDirectory now returns undefined) I understand this all is super fresh.

**Comment by brentvatne** [comment]
heya! check out the latest version. it should work as expected again, and i also fixed expo-asset so that it works outside of expo context and so does expo-font

**Comment by zubko** [comment]
Thanks for a super quick fix! Both assets and documentDirectory are working now.
The idea to have a reusable native modules infrastructure which can build on top of each other looks very promising!
